server.port=8080

spring.application.name=auth-service
spring.config.import=optional:file:./auth-service/.env[.properties]

spring.rabbitmq.host=${RABBIT_MQ_HOST}
spring.rabbitmq.port=${RABBIT_MQ_PORT}
spring.rabbitmq.username=${RABBIT_MQ_USER}
spring.rabbitmq.password=${RABBIT_MQ_PASSWORD}

spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.concurrency=${RABBIT_MQ_CONCURRENCY}
spring.rabbitmq.listener.simple.max-concurrency=${RABBIT_MQ_MAX_CONCURRENCY}