spring.application.name=user-service
spring.config.import=optional:file:./user-service/.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
liquibase.liquibaseSchema=${DB_SCHEMA}
liquibase.defaultSchema=${DB_SCHEMA}

spring.rabbitmq.host=${RABBIT_MQ_HOST}
spring.rabbitmq.port=${RABBIT_MQ_PORT}
spring.rabbitmq.username=${RABBIT_MQ_USER}
spring.rabbitmq.password=${RABBIT_MQ_PASSWORD}

# Optional but useful
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.concurrency=${RABBIT_MQ_CONCURRENCY}
spring.rabbitmq.listener.simple.max-concurrency=${RABBIT_MQ_MAX_CONCURRENCY}